### ISSUE TITLE
Android GenerateKalturaClient log4j Error

### ISSUE THREAD

**Issue by sharadhihosamani** [kaltura/KalturaGeneratedAPIClientsJava#21]
Hi ,

I am using **kalturaApiClient:17.1.1** (https://mvnrepository.com/artifact/com.kaltura/kalturaApiClient/17.1.1 ) in my android application as a gradle dependency:  
// https://mvnrepository.com/artifact/com.kaltura/kalturaApiClient
implementation 'com.kaltura:kalturaApiClient:17.1.1'

While generating Kaltura Client using following code :

   private fun generateKalturaClient(): Client {
            val config = Configuration()
            config.endpoint = "https://www.kaltura.com/"
            return Client(config)
    }

I am getting below error:

<img width="1502" alt="Screenshot 2021-08-10 at 2 52 29 PM" src="https://user-images.githubusercontent.com/22168878/128842648-f1da2f44-6b9c-4d6b-8fbe-85bd6c85bbd3.png">

Min SDK version: 28(API 28: Android 9.0)
Max SDK version: 30 (API 30: Android 11.0)

Regards,
Sharadhi Hosamani

**Comment by kaltura-hooks** [comment]
Hi @sharadhihosamani,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa \"kaltura*\"
```	
	For deb based systems:
```	
	# dpkg -l \"kaltura-*\"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color \"ERR:\|PHP\|trace\|CRIT\|\[error\]\"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by sharadhihosamani** [comment]
The above details did not fix the issue. I am using the KalturaAPIClient in an android app as a gradle dependency as mentioned in the ticket details.

**Comment by sharadhihosamani** [comment]
Used "kalturaClient" instead of "kalturaApiClient" https://mvnrepository.com/artifact/com.kaltura/kalturaClient/3.2.1
