### ISSUE TITLE
Error when converting uploaded file

### ISSUE THREAD

**Issue by moskiteau** [kaltura/KalturaGeneratedAPIClientsJava#6]
Hello,

Kaltura SAAS Hercule hosted on rackforcecloudvideo.com

I am trying to upload a big file using chunked upload. I litterally copied and pasted the code from the android project

https://raw.githubusercontent.com/kaltura/AndroidReferenceApp/master/DemoApplication/src/com/kaltura/services/UploadToken.java

I just removed unused code such as 
```
setChanged();
notifyObservers(getUploadedFileSize());
```
The upload and converting works well with small/medium size files, anything under 2G actually.

But with a 3.1G file, the upload is still working, I can see the file in the admin «converting». But after a while It falls in error and the contibution file (the uploaded file) hasn't been rebuilt into an mp4; it's a .dat

![screenshot of kmc](http://oi64.tinypic.com/2w66n3r.jpg)

Thank you

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,

Thank for you reporting an issue and helping improve Kaltura!

To get the fastest response time, and help the maintainers review and test your reported issues or suggestions, please ensure that your issue includes the following (please comment with more info if you have not included all this info in your original issue):
 - Is the issue you're experiencing consistent and across platforms? or does it only happens on certain conditions?
    please provide as much details as possible.
 - Which Kaltura deployment you're using: Kaltura SaaS, or self-hosted?
	If self hosted, are you using the RPM or deb install?
 - Packages installed.
	When using RPM, paste the output for:
```
	# rpm -qa "kaltura*"
```	
	For deb based systems:
```	
	# dpkg -l "kaltura-*"
```
 - If running a self hosted ENV - provide the MySQL server version used
 - If running a self hosted ENV - is this a single all in 1 server or a cluster?
 - If running a self hosted ENV, while making the problematic request, run:
```
	# tail -f /opt/kaltura/log/*.log /opt/kaltura/log/batch/*.log | grep -A 1 -B 1 --color "ERR:\|PHP\|trace\|CRIT\|\[error\]"
```
   and paste the output.
 - When relevant, provide any screenshots or screen recordings showing the issue you're experiencing.

For general troubleshooting see:
https://github.com/kaltura/platform-install-packages/blob/Jupiter-10.13.0/doc/kaltura-packages-faq.md#troubleshooting-help

If you only have a general question rather than a bug report, please close this issue and post at:
http://forum.kaltura.org

Thank you in advance,

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsJava is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by kaltura-hooks** [comment]
Hi @moskiteau,
Thank you for contributing this pull request!
The KalturaGeneratedAPIClientsJava is autogenerated from https://github.com/kaltura/server under generator/sources/__LANG__
Please create a new pull on the server repo.

**Comment by jessp01** [comment]
Closing in favor of https://github.com/kaltura/server/issues/3549
